<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130405174348 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE post ADD category_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)");
        $this->addSql("CREATE INDEX IDX_5A8A6C8D12469DE2 ON post (category_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8D12469DE2");
        $this->addSql("DROP INDEX IDX_5A8A6C8D12469DE2 ON post");
        $this->addSql("ALTER TABLE post DROP category_id");
    }
}
