parameters:
#    dev_this_default.example.class: DevThis\DefaultBundle\Example

services:
#    dev_this_default.example:
#        class: %dev_this_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
